Add shopping cart integration
YaroslavYarmoshyk/book-store pull request #9
Opened 2024-03-21 11:42 UTC by YaroslavYarmoshyk

2024-03-21 18:30 UTC, Vasul-Pankiv requested changes
Great Job

2024-03-21 18:30 UTC, Vasul-Pankiv commented on src/main/java/com/online/bookstore/model/CartItem.java
> +    @OneToOne
```suggestion
    @ManyToOne
```

2024-03-21 18:30 UTC, Vasul-Pankiv commented on src/main/java/com/online/bookstore/mapper/CartItemMapper.java
> +
Do not start class with empty line

2024-03-21 18:30 UTC, Vasul-Pankiv commented on src/main/java/com/online/bookstore/mapper/CartItemMapper.java
> +
fix it everywhere

2024-03-22 12:22 UTC, kerrrusha approved these changes

2024-03-22 12:50 UTC, merged